/**
 * Catalog entries tool00101 … tool00500 (400 tools).
 * Requires: const { spec } = require('./tools-en-catalog');
 */
function defaultPain(name) {
  return `${name} solves a focused task you need often—fast, free, and without uploading data.`;
}

function defaultFns() {
  return ['Paste or enter input', 'Run in browser', 'Copy the result', 'No account required'];
}

function row(id, name, category, subcategory, kind, keywords, pain, functions, audience) {
  const { spec } = require('./tools-en-catalog');
  return spec(
    id,
    name,
    category,
    subcategory,
    kind,
    keywords,
    pain || defaultPain(name),
    functions || defaultFns(),
    audience || 'developers, creators, and office users'
  );
}

function batch2() {
  const PDF = 'PDF & Documents';
  const IMG = 'Image & Media';
  const TXT = 'Text & Writing';
  const pdf = (id, name, kind, kw) => row(id, name, PDF, 'PDF Tools', kind, kw);
  const img = (id, name, kind, kw) => row(id, name, IMG, 'Image Tools', kind, kw);
  const txt = (id, name, kind, kw) => row(id, name, TXT, 'Text Tools', kind, kw);
  return [
    pdf(101, 'PDF Page Counter', 'pdf-page-count', ['pdf page count', 'count pdf pages', 'pdf pages']),
    pdf(102, 'PDF Merge Text Planner', 'pdf-merge-plan', ['merge pdf', 'combine pdf pages', 'pdf merge plan']),
    pdf(103, 'PDF Split by Page Range Planner', 'pdf-split-plan', ['split pdf', 'pdf page range', 'extract pdf pages']),
    pdf(104, 'PDF Rotate Pages Planner', 'pdf-rotate-plan', ['rotate pdf', 'pdf orientation', 'rotate pdf pages']),
    pdf(105, 'PDF Metadata Stripper Guide', 'pdf-meta-guide', ['remove pdf metadata', 'pdf metadata', 'strip pdf meta']),
    pdf(106, 'Images to PDF Layout Planner', 'img-pdf-plan', ['images to pdf', 'jpg to pdf layout', 'photo pdf']),
    pdf(107, 'PDF to Images Extract Plan', 'pdf-img-plan', ['pdf to jpg', 'pdf to images', 'extract pdf images']),
    pdf(108, 'PDF Page Size Checker', 'pdf-size-check', ['pdf page size', 'pdf dimensions', 'letter a4 pdf']),
    pdf(109, 'PDF Bookmark Outline Generator', 'pdf-outline', ['pdf bookmarks', 'pdf outline', 'pdf toc']),
    pdf(110, 'PDF Linearize Checklist', 'pdf-checklist', ['optimize pdf web', 'linearize pdf', 'fast web pdf']),
    pdf(111, 'Print CSS to PDF Tips', 'print-pdf-tips', ['print to pdf css', 'print stylesheet', 'css pdf']),
    pdf(112, 'PDF Font Embed Checker', 'pdf-font-check', ['pdf fonts', 'embed fonts pdf', 'pdf font checklist']),
    pdf(113, 'PDF Color Space Notes', 'pdf-color-space', ['pdf rgb cmyk', 'pdf color space', 'print color pdf']),
    pdf(114, 'PDF Form Field Renamer', 'pdf-field-rename', ['pdf form fields', 'rename pdf fields', 'pdf forms']),
    pdf(115, 'PDF Page Label Generator', 'pdf-page-labels', ['pdf page numbers', 'pdf labels', 'bates numbering']),
    pdf(116, 'PDF Annotation Summary', 'pdf-annot-summary', ['pdf comments', 'pdf annotations', 'export pdf notes']),
    pdf(117, 'PDF Version Compatibility', 'pdf-version', ['pdf version', 'pdf 1.7', 'pdf compatibility']),
    pdf(118, 'PDF Byte Size Estimator', 'pdf-size-est', ['pdf file size', 'estimate pdf size', 'pdf mb']),
    pdf(119, 'PDF Crop Box Calculator', 'pdf-crop', ['pdf crop', 'crop box pdf', 'pdf margins']),
    pdf(120, 'PDF Bleed Margin Calculator', 'pdf-bleed', ['pdf bleed', 'print bleed', 'bleed margins']),
    pdf(121, 'PDF N-up Imposition Planner', 'pdf-nup', ['pdf 2up', 'pdf 4up', 'imposition pdf']),
    pdf(122, 'PDF Grayscale Planner', 'pdf-grayscale', ['grayscale pdf', 'black white pdf', 'mono pdf']),
    pdf(123, 'PDF Password Strength Tips', 'pdf-password-tips', ['pdf password', 'secure pdf password', 'encrypt pdf']),
    pdf(124, 'PDF/A Checklist Generator', 'pdf-a-checklist', ['pdf/a', 'archive pdf', 'pdf compliance']),
    pdf(125, 'Accessible PDF Checklist', 'pdf-a11y-check', ['accessible pdf', 'pdf accessibility', 'pdf a11y']),
    img(126, 'PNG to JPG Converter', 'img-format-note', ['png to jpg', 'convert png jpg', 'image format']),
    img(127, 'JPG to PNG Converter', 'img-format-note', ['jpg to png', 'convert jpg png', 'jpeg png']),
    img(128, 'WebP to PNG Converter', 'img-format-note', ['webp to png', 'convert webp', 'webp png']),
    img(129, 'PNG to WebP Converter', 'img-format-note', ['png to webp', 'convert webp', 'webp optimize']),
    img(130, 'Image Resize by Width', 'img-resize-calc', ['resize image width', 'image pixels', 'scale image']),
    img(131, 'Image Resize by Percent', 'img-resize-calc', ['resize image percent', 'scale percent', 'image scale']),
    img(132, 'Image Compress Quality Estimator', 'img-quality-est', ['image compression', 'jpeg quality', 'compress image']),
    img(133, 'Image DPI / Pixel Size Calculator', 'img-dpi-calc', ['image dpi', 'pixels to inches', 'print dpi']),
    img(134, 'EXIF Stripper Checklist', 'img-exif-check', ['remove exif', 'strip metadata image', 'exif privacy']),
    img(135, 'Dominant Color Extractor', 'img-dominant-note', ['dominant color', 'color palette image', 'extract colors']),
    img(136, 'Image Base64 Size Calculator', 'base64-image', ['base64 image size', 'data url size', 'image base64']),
    img(137, 'Favicon Generator Planner', 'favicon-plan', ['favicon sizes', 'favicon generator', 'site icon']),
    img(138, 'Open Graph Image Size Checker', 'og-image-size', ['og image size', 'open graph dimensions', 'social image size']),
    img(139, 'Image Aspect Crop Calculator', 'aspect-ratio', ['crop aspect ratio', 'image crop ratio', 'aspect calculator']),
    img(140, 'Hex from Image Upload', 'img-hex-note', ['color from image', 'image hex color', 'pick color image']),
    img(141, 'Image Filename SEO Renamer', 'img-rename-seo', ['seo image filename', 'rename images seo', 'image file names']),
    img(142, 'SVG to PNG Export Planner', 'svg-export-plan', ['svg to png', 'export svg', 'vector to png']),
    img(143, 'GIF Frame Count Estimator', 'gif-info', ['gif frames', 'gif duration', 'animated gif info']),
    img(144, 'ICO Size Checklist', 'ico-checklist', ['ico sizes', 'favicon ico', 'windows icon']),
    img(145, 'Image Brightness/Contrast Formula', 'img-bc-formula', ['brightness contrast', 'image formula', 'adjust levels']),
    img(146, 'Pixel Aspect Ratio Calculator', 'pixel-aspect', ['pixel aspect ratio', 'par calculator', 'video pixels']),
    img(147, 'Thumbnail Grid Spec Generator', 'thumb-grid', ['thumbnail grid', 'gallery thumbnails', 'image grid']),
    img(148, 'Image Alt Text Batch Template', 'alt-batch', ['alt text generator', 'image alt template', 'accessibility alt']),
    img(149, 'Lazy Load img Tag Generator', 'lazy-img-tag', ['lazy loading image', 'loading lazy html', 'img lazy']),
    img(150, 'srcset Generator', 'srcset-gen', ['srcset generator', 'responsive images', 'html srcset']),
    img(151, 'Picture Element Generator', 'picture-gen', ['picture element', 'responsive picture', 'html picture']),
    img(152, 'Image File Size Compare', 'img-size-compare', ['compare image size', 'file size images', 'image kb']),
    img(153, 'CMYK to RGB Preview Formula', 'color-convert', ['cmyk to rgb', 'print color convert', 'cmyk rgb']),
    img(154, 'Image Hash Perceptual Note', 'img-hash-note', ['perceptual hash', 'image hash', 'duplicate image']),
    img(155, 'Bulk Image Dimension Parser', 'img-dim-parse', ['image dimensions list', 'width height batch', 'image sizes']),
    txt(156, 'Lorem Ipsum Generator', 'lorem-gen', ['lorem ipsum', 'placeholder text', 'dummy text']),
    txt(157, 'Readability Score (Flesch)', 'readability', ['readability score', 'flesch reading', 'readability test']),
    txt(158, 'Line Ending Converter (CRLF/LF)', 'line-ending', ['crlf lf', 'line ending converter', 'windows unix lines']),
    txt(159, 'Trim Whitespace Lines', 'trim-lines', ['trim lines', 'remove whitespace', 'clean lines']),
    txt(160, 'Extract URLs from Text', 'url-extract', ['extract urls', 'find links in text', 'url list']),
    txt(161, 'Extract Emails from Text', 'email-extract', ['extract emails', 'find email addresses', 'email list']),
    txt(162, 'Extract Hashtags', 'hashtag-extract', ['extract hashtags', 'find hashtags', 'social tags']),
    txt(163, 'Slugify Batch Lines', 'slug-batch', ['slugify list', 'batch slug', 'url slug batch']),
    txt(164, 'Title Case Converter', 'title-case-en', ['title case', 'capitalize title', 'english title case']),
    txt(165, 'Sentence Case Converter', 'sentence-case', ['sentence case', 'capitalize sentence', 'text case']),
    txt(166, 'Reverse Text', 'reverse-text', ['reverse text', 'flip string', 'backwards text']),
    txt(167, 'Remove HTML Tags', 'strip-html', ['strip html', 'remove tags', 'html to text']),
    txt(168, 'Markdown to Plain Text', 'md-plain', ['markdown to text', 'strip markdown', 'plain text md']),
    txt(169, 'Plain Text to HTML Paragraphs', 'text-to-html', ['text to html', 'paragraphs html', 'plain to html']),
    txt(170, 'Word Frequency Counter', 'word-freq', ['word frequency', 'word count list', 'term frequency']),
    txt(171, 'Character Frequency Counter', 'char-freq', ['character frequency', 'letter count', 'char stats']),
    txt(172, 'Reading Level Estimator', 'reading-level', ['reading level', 'grade level text', 'readability level']),
    txt(173, 'Syllable Counter (English)', 'syllable-count', ['syllable counter', 'count syllables', 'english syllables']),
    txt(174, 'Palindrome Checker', 'palindrome', ['palindrome checker', 'is palindrome', 'reverse word']),
    txt(175, 'Anagram Sorter', 'anagram', ['anagram sort', 'anagram checker', 'rearrange letters']),
    txt(176, 'Citation APA Quick Formatter', 'cite-apa', ['apa citation', 'apa format', 'citation generator']),
    txt(177, 'Meta Description Generator from Bullets', 'meta-gen-bullets', ['meta description generator', 'seo description', 'meta from bullets']),
    txt(178, 'Blog Outline from Keywords', 'outline-gen', ['blog outline', 'content outline', 'keyword outline']),
    txt(179, 'FAQ from Bullet Points', 'faq-expand', ['faq generator', 'expand faq', 'faq from bullets']),
    txt(180, 'Privacy Policy Clause Picker', 'privacy-clauses', ['privacy policy clauses', 'privacy template', 'gdpr clauses'])
  ];
}

function batch3() {
  const CALC = 'Calculators & Units';
  const CONV = 'Converters (format/data)';
  const IMG = 'Image & Media';
  const calc = (id, name, kind, kw) => row(id, name, CALC, 'Math & Units', kind, kw);
  const conv = (id, name, kind, kw) => row(id, name, CONV, 'Data Formats', kind, kw);
  const img = (id, name, kind, kw) => row(id, name, IMG, 'Image Tools', kind, kw);
  const items = [
    calc(181, 'BMI Calculator', 'bmi-calc', ['bmi calculator', 'body mass index', 'bmi metric']),
    calc(182, 'BMR Calculator', 'bmr-calc', ['bmr calculator', 'basal metabolic rate', 'calorie bmr']),
    calc(183, 'Loan Monthly Payment Calculator', 'loan-calc', ['loan calculator', 'monthly payment', 'amortization']),
    calc(184, 'Compound Interest Calculator', 'compound-calc', ['compound interest', 'savings calculator', 'interest rate']),
    calc(185, 'Tip Calculator', 'tip-calc', ['tip calculator', 'gratuity calculator', 'split bill tip']),
    calc(186, 'Discount Stack Calculator', 'discount-calc', ['discount calculator', 'stacked discount', 'sale price']),
    calc(187, 'Profit Margin Calculator', 'margin-calc', ['profit margin', 'margin calculator', 'markup margin']),
    calc(188, 'Markup Price Calculator', 'markup-calc', ['markup calculator', 'price markup', 'retail markup']),
    calc(189, 'Currency Convert (Manual Rate)', 'currency-calc', ['currency converter', 'exchange rate calc', 'manual rate']),
    calc(190, 'Kilometers to Miles', 'unit-convert', ['km to miles', 'kilometer mile', 'length convert']),
    calc(191, 'Miles to Kilometers', 'unit-convert', ['miles to km', 'mile kilometer', 'length convert']),
    calc(192, 'Pounds to Kilograms', 'unit-convert', ['lb to kg', 'pounds kilograms', 'weight convert']),
    calc(193, 'Celsius to Fahrenheit', 'unit-convert', ['celsius fahrenheit', 'temperature convert', 'c to f']),
    calc(194, 'Fahrenheit to Celsius', 'unit-convert', ['fahrenheit celsius', 'f to c', 'temperature']),
    calc(195, 'Square Meters to Square Feet', 'unit-convert', ['sqm to sqft', 'area convert', 'm2 ft2']),
    calc(196, 'Liters to Gallons', 'unit-convert', ['liters gallons', 'volume convert', 'liter gallon']),
    calc(197, 'Binary to Decimal', 'unit-convert', ['binary decimal', 'bin to dec', 'number base']),
    calc(198, 'Decimal to Binary', 'unit-convert', ['decimal binary', 'dec to bin', 'base 2']),
    calc(199, 'Bytes to Megabytes (SI)', 'unit-convert', ['bytes to mb', 'data size convert', 'file size si']),
    calc(200, 'Megabytes to Gigabytes (IEC)', 'unit-convert', ['mb to gb', 'binary size', 'iec units']),
    calc(201, 'Mbps to MB/s Calculator', 'unit-convert', ['mbps to mbs', 'network speed', 'download speed']),
    calc(202, 'Fuel Cost Trip Calculator', 'fuel-calc', ['fuel cost trip', 'gas trip calculator', 'mileage cost']),
    calc(203, 'Calorie Burn Estimator', 'calorie-calc', ['calorie burn', 'exercise calories', 'activity calories']),
    calc(204, 'Shoe Size US EU UK Chart', 'size-chart', ['shoe size converter', 'us eu shoe', 'shoe chart']),
    calc(205, 'Clothing Size Converter', 'size-chart', ['clothing size', 'apparel size chart', 'size convert']),
    calc(206, 'Age Calculator', 'age-calc', ['age calculator', 'birthday age', 'years old']),
    calc(207, 'Days Between Dates', 'date-diff', ['days between dates', 'date difference', 'day counter']),
    calc(208, 'Workdays Estimator', 'workdays-calc', ['workdays calculator', 'business days', 'weekday count']),
    calc(209, 'Add Days to Date', 'date-add', ['add days date', 'date plus days', 'future date']),
    calc(210, 'Percentage of Total', 'percent-calc', ['percentage of', 'percent total', 'ratio percent']),
    calc(211, 'Ratio Calculator', 'ratio-calc', ['ratio calculator', 'aspect ratio math', 'proportion']),
    calc(212, 'Square Root Calculator', 'sqrt-calc', ['square root', 'sqrt calculator', 'root math']),
    calc(213, 'Scientific Notation Converter', 'sci-notation', ['scientific notation', 'e notation', 'exp format']),
    calc(214, 'Fraction Simplifier', 'fraction-calc', ['simplify fraction', 'reduce fraction', 'lowest terms']),
    calc(215, 'GCD and LCM Calculator', 'gcd-lcm', ['gcd lcm', 'greatest common divisor', 'least common multiple']),
    conv(216, 'JSON to XML Converter', 'json-xml', ['json to xml', 'xml from json', 'convert json xml']),
    conv(217, 'XML to JSON Converter', 'json-xml', ['xml to json', 'convert xml json', 'parse xml json']),
    conv(218, 'TSV to CSV Converter', 'tsv-csv', ['tsv to csv', 'tab to comma', 'convert tsv']),
    conv(219, 'CSV to TSV Converter', 'tsv-csv', ['csv to tsv', 'comma to tab', 'convert csv tsv']),
    conv(220, 'INI to JSON Converter', 'ini-json', ['ini to json', 'ini parser', 'config ini json']),
    conv(221, 'JSON to INI Converter', 'ini-json', ['json to ini', 'ini export', 'config ini']),
    conv(222, 'TOML to JSON Converter', 'toml-json', ['toml to json', 'toml parser', 'config toml']),
    conv(223, 'HTML Table to CSV', 'html-table-csv', ['html table csv', 'table to csv', 'extract table']),
    conv(224, 'BBCode to HTML Converter', 'bbcode-html', ['bbcode to html', 'forum markup', 'bbcode convert']),
    conv(225, 'Emoji to Unicode Codepoints', 'emoji-unicode', ['emoji unicode', 'codepoint emoji', 'emoji hex']),
    conv(226, 'Punycode Encoder', 'punycode', ['punycode encode', 'idn domain', 'unicode domain']),
    conv(227, 'Morse Code Encoder', 'morse-code', ['morse code', 'text to morse', 'morse encoder']),
    conv(228, 'Binary Text Encoder', 'binary-text', ['text to binary', 'binary encode', 'ascii binary']),
    conv(229, 'Hex Text Encoder', 'hex-text', ['text to hex', 'hex encode', 'string hex']),
    conv(230, 'Octal Decimal Converter', 'octal-dec', ['octal decimal', 'base 8 convert', 'octal to dec']),
    conv(231, 'Roman Numeral Converter', 'roman-num', ['roman numerals', 'roman to number', 'number roman']),
    conv(232, 'Number to Words (English)', 'num-words', ['number to words', 'spell number', 'english number words']),
    conv(233, 'CSV Delimiter Detector', 'csv-detect', ['csv delimiter', 'detect separator', 'tsv semicolon']),
    conv(234, 'Properties to JSON', 'props-json', ['properties json', 'java properties json', 'key value json']),
    conv(235, 'JSON to Properties', 'props-json', ['json properties', 'export properties', 'config properties']),
    img(236, 'Image Crop Ratio 16:9', 'aspect-ratio', ['16:9 crop', 'crop ratio', 'widescreen crop']),
    img(237, 'Image Crop Ratio 4:3', 'aspect-ratio', ['4:3 aspect', 'photo crop ratio', 'standard crop']),
    img(238, 'CSS box-shadow Generator', 'box-shadow-gen', ['box shadow css', 'css shadow generator', 'drop shadow']),
    img(239, 'CSS border-radius Generator', 'border-radius-gen', ['border radius css', 'rounded corners css', 'radius generator']),
    img(240, 'CSS clip-path Generator', 'clip-path-gen', ['clip path css', 'css shape clip', 'polygon clip']),
    img(241, 'CSS Gradient Generator', 'gradient-gen', ['css gradient', 'linear gradient generator', 'background gradient']),
    img(242, 'Color Blindness Simulator Note', 'colorblind-note', ['color blindness', 'protanopia', 'accessibility color']),
    img(243, 'Image Sharpening Formula Note', 'img-sharpen-note', ['sharpen image', 'unsharp mask', 'image sharpen']),
    img(244, 'Contrast Curve Explainer', 'contrast-note', ['contrast curve', 'image contrast', 'tone curve']),
    img(245, 'Watermark Position Calculator', 'watermark-calc', ['watermark position', 'image watermark', 'overlay position']),
    img(246, 'Social Media Image Sizes', 'social-size-chart', ['social image sizes', 'instagram size', 'twitter image size']),
    img(247, 'App Store Screenshot Sizes', 'app-screenshot-chart', ['app screenshot size', 'ios screenshot', 'play store image']),
    img(248, 'Sprite Sheet Grid Calculator', 'sprite-calc', ['sprite sheet', 'sprites grid', 'game sprites']),
    img(249, 'Image DPI for Print Calculator', 'img-dpi-calc', ['print dpi', '300 dpi print', 'image print size']),
    img(250, 'Aspect Fit vs Fill Explainer', 'aspect-fit-note', ['object fit', 'aspect fit fill', 'css object-fit']),
    img(251, 'WebP Quality Size Estimator', 'img-quality-est', ['webp quality', 'webp size', 'webp compress']),
    img(252, 'AVIF Format Checklist', 'avif-checklist', ['avif format', 'next gen image', 'avif browser']),
    img(253, 'PNG Optimization Checklist', 'png-checklist', ['optimize png', 'png compression', 'png size']),
    img(254, 'JPEG Chroma Subsampling Note', 'jpeg-chroma-note', ['jpeg chroma', 'jpeg quality', 'subsampling 4:2:0']),
    img(255, 'Image CDN URL Template', 'cdn-url-template', ['image cdn url', 'cdn template', 'asset url']),
    img(256, 'Responsive Breakpoints Planner', 'breakpoints-plan', ['responsive breakpoints', 'media queries', 'css breakpoints']),
    img(257, 'Hero Image Crop Safe Area', 'hero-crop-note', ['hero image crop', 'banner safe area', 'header image']),
    img(258, 'Product Image Gallery Spec', 'gallery-spec', ['product gallery', 'ecommerce images', 'gallery spec']),
    img(259, 'Image Sitemap Entry Generator', 'image-sitemap', ['image sitemap', 'image seo', 'sitemap image']),
    img(260, 'Bulk Rename Pattern Generator', 'bulk-rename', ['bulk rename', 'file rename pattern', 'batch rename'])
  ];
  return items;
}

function batch4() {
  const DEV = 'Development & Data';
  const SEO = 'SEO & Webmasters';
  const REF = 'Reference & Codes';
  const TIME = 'Date, Time & Timezone';
  const d = (id, name, sub, kind, kw) => row(id, name, DEV, sub, kind, kw);
  const s = (id, name, sub, kind, kw) => row(id, name, SEO, sub, kind, kw);
  const r = (id, name, sub, kind, kw) => row(id, name, REF, sub, kind, kw);
  const t = (id, name, sub, kind, kw) => row(id, name, TIME, sub, kind, kw);
  return [
    d(261, 'OpenAPI Path Lister', 'API Tools', 'openapi-list', ['openapi paths', 'api routes list', 'swagger paths']),
    d(262, 'GraphQL Query Formatter', 'API Tools', 'graphql-format', ['graphql formatter', 'format graphql', 'gql query']),
    d(263, 'Protobuf Text Formatter', 'API Tools', 'proto-format', ['protobuf text', 'proto format', 'pb txt']),
    d(264, 'LDAP DN Parser', 'API Tools', 'ldap-dn', ['ldap dn', 'distinguished name', 'ldap parse']),
    d(265, 'Cron Next Runs Preview', 'Time & Encoding', 'cron-next', ['cron next run', 'cron schedule times', 'when cron runs']),
    d(266, 'Semver Compare Tool', 'CLI Helpers', 'semver-compare', ['semver compare', 'version compare', 'npm version']),
    d(267, 'docker-compose Snippet Builder', 'Config Generators', 'compose-snippet', ['docker compose', 'compose yaml', 'multi container']),
    d(268, 'systemd Unit Snippet Builder', 'Config Generators', 'systemd-snippet', ['systemd unit', 'service file', 'linux systemd']),
    d(269, 'gitignore Generator', 'Config Generators', 'gitignore-gen', ['gitignore generator', 'git ignore', 'project gitignore']),
    d(270, 'EditorConfig Generator', 'Config Generators', 'editorconfig-gen', ['editorconfig', 'ide config', 'coding style file']),
    d(271, 'Prettier Config Snippet', 'Config Generators', 'prettier-snippet', ['prettier config', 'prettier json', 'format config']),
    d(272, 'ESLint Flat Config Snippet', 'Config Generators', 'eslint-snippet', ['eslint config', 'eslint flat', 'lint config']),
    d(273, 'Nginx Rate Limit Config', 'Config Generators', 'nginx-rate', ['nginx rate limit', 'limit_req', 'nginx throttle']),
    d(274, 'CORS Header Builder', 'API Debugging', 'cors-builder', ['cors headers', 'access-control-allow', 'cors config']),
    d(275, 'Content-Type Matcher', 'API Debugging', 'content-type-match', ['content type', 'mime match', 'accept header']),
    d(276, 'MIME from File Extension', 'Network Tools', 'mime-ext', ['mime type extension', 'file mime', 'content type lookup']),
    d(277, 'bcrypt Cost Explainer', 'Security', 'bcrypt-note', ['bcrypt cost', 'password hash cost', 'bcrypt rounds']),
    d(278, 'SSH Key Format Checker', 'Security', 'ssh-key-check', ['ssh key format', 'openssh key', 'rsa ed25519']),
    d(279, 'PEM Certificate Expiry Decoder', 'Security', 'pem-decode', ['pem certificate', 'cert expiry', 'x509 decode']),
    d(280, 'IPv6 Shorten / Expand', 'Network Tools', 'ipv6-format', ['ipv6 shorten', 'ipv6 expand', 'compress ipv6']),
    d(281, 'MAC Address Formatter', 'Network Tools', 'mac-format', ['mac address format', 'normalize mac', 'oui mac']),
    d(282, 'CIDR Overlap Checker', 'Network Tools', 'cidr-overlap', ['cidr overlap', 'subnet overlap', 'ip range clash']),
    d(283, 'Port Range Validator', 'Network Tools', 'port-range', ['port range', 'valid ports', 'firewall ports']),
    d(284, 'HTTP Method Semantics', 'API Debugging', 'http-method-ref', ['http methods', 'get post put', 'rest methods']),
    d(285, 'Webhook Retry Backoff Planner', 'API Debugging', 'retry-plan', ['exponential backoff', 'webhook retry', 'retry schedule']),
    s(286, 'Schema.org Type Picker', 'Structured Data', 'schema-picker', ['schema.org types', 'structured data type', 'json-ld type']),
    s(287, 'Breadcrumb JSON-LD Generator', 'Structured Data', 'breadcrumb-schema', ['breadcrumb schema', 'breadcrumb json-ld', 'breadcrumbs seo']),
    s(288, 'Article JSON-LD Generator', 'Structured Data', 'article-schema', ['article schema', 'article json-ld', 'blog schema']),
    s(289, 'HowTo JSON-LD Generator', 'Structured Data', 'howto-schema', ['howto schema', 'howto json-ld', 'tutorial schema']),
    s(290, 'VideoObject JSON-LD Generator', 'Structured Data', 'video-schema', ['video schema', 'videoobject json-ld', 'video seo']),
    s(291, 'Organization JSON-LD Generator', 'Structured Data', 'org-schema', ['organization schema', 'company json-ld', 'org seo']),
    s(292, 'WebSite SearchAction JSON-LD', 'Structured Data', 'website-schema', ['website schema', 'searchaction', 'sitelinks search']),
    s(293, 'Meta Robots Tag Builder', 'Technical SEO', 'meta-robots', ['meta robots', 'noindex nofollow', 'robots tag']),
    s(294, 'X-Robots-Tag Header Builder', 'Technical SEO', 'x-robots', ['x-robots-tag', 'header robots', 'noindex header']),
    s(295, 'rel=alternate Link Generator', 'Technical SEO', 'rel-alternate', ['rel alternate', 'alternate link', 'media alternate']),
    s(296, 'Pagination rel next/prev', 'Technical SEO', 'rel-pagination', ['rel next prev', 'pagination seo', 'paginated pages']),
    s(297, 'Title Pixel Width Estimator', 'On-Page SEO', 'title-pixel', ['title pixel width', 'serp title width', 'google title pixels']),
    s(298, 'Description Pixel Width Estimator', 'On-Page SEO', 'desc-pixel', ['meta description pixels', 'serp description width', 'snippet width']),
    s(299, 'Keyword Density Checker', 'On-Page SEO', 'keyword-density', ['keyword density', 'term frequency seo', 'word density']),
    s(300, 'Heading Keyword Presence Check', 'On-Page SEO', 'heading-kw', ['heading keywords', 'h1 keyword', 'headings seo']),
    s(301, 'Outbound nofollow Link Generator', 'Internal Links', 'nofollow-gen', ['nofollow link', 'rel nofollow', 'external link seo']),
    s(302, 'Affiliate Link Disclaimer Text', 'On-Page SEO', 'affiliate-disclaimer', ['affiliate disclaimer', 'sponsored link text', 'affiliate disclosure']),
    s(303, 'Faceted Nav noindex Guide', 'Technical SEO', 'faceted-seo', ['faceted navigation', 'noindex filters', 'ecommerce seo filters']),
    s(304, 'Thin Content Audit Checklist', 'Technical SEO', 'thin-content', ['thin content', 'content quality audit', 'low value pages']),
    s(305, 'E-E-A-T Page Checklist', 'Technical SEO', 'eeat-checklist', ['eeat checklist', 'experience expertise', 'trust content']),
    r(306, 'HTTP 404 Not Found Reference', 'HTTP Status', 'http-ref', ['http 404', '404 meaning', 'not found status']),
    r(307, 'HTTP 403 Forbidden Reference', 'HTTP Status', 'http-ref', ['http 403', '403 forbidden', 'access denied']),
    r(308, 'HTTP 401 Unauthorized Reference', 'HTTP Status', 'http-ref', ['http 401', 'unauthorized', 'auth required']),
    r(309, 'HTTP 422 Unprocessable Entity', 'HTTP Status', 'http-ref', ['http 422', 'unprocessable entity', 'validation error']),
    r(310, 'HTTP 429 Too Many Requests', 'HTTP Status', 'http-ref', ['http 429', 'rate limit', 'too many requests']),
    r(311, 'HTTP 500 Internal Server Error', 'HTTP Status', 'http-ref', ['http 500', 'server error', 'internal error']),
    r(312, 'HTTP 502 Bad Gateway Reference', 'HTTP Status', 'http-ref', ['http 502', 'bad gateway', 'proxy error']),
    r(313, 'HTTP 503 Service Unavailable', 'HTTP Status', 'http-ref', ['http 503', 'service unavailable', 'maintenance']),
    r(314, 'Port 443 HTTPS Reference', 'Ports', 'port-ref', ['port 443', 'https port', 'ssl port']),
    r(315, 'Port 80 HTTP Reference', 'Ports', 'port-ref', ['port 80', 'http port', 'web port']),
    r(316, 'Port 22 SSH Reference', 'Ports', 'port-ref', ['port 22', 'ssh port', 'secure shell']),
    r(317, 'Port 3306 MySQL Reference', 'Ports', 'port-ref', ['port 3306', 'mysql port', 'database port']),
    r(318, 'Port 5432 PostgreSQL Reference', 'Ports', 'port-ref', ['port 5432', 'postgres port', 'postgresql port']),
    r(319, 'MIME type text/html Reference', 'MIME Types', 'mime-ref', ['mime text html', 'content type html', 'text/html']),
    r(320, 'MIME type application/json', 'MIME Types', 'mime-ref', ['application json', 'json mime', 'api json type']),
    r(321, 'Git Exit Code 128 Reference', 'Error Codes', 'git-exit-ref', ['git exit code', 'git error 128', 'git failed']),
    r(322, 'npm ERR! Code Reference', 'Error Codes', 'npm-err-ref', ['npm error code', 'npm err', 'npm install error']),
    r(323, 'PostgreSQL Error Class 42', 'Error Codes', 'pg-class-ref', ['postgresql error', 'sql state 42', 'syntax error sql']),
    r(324, 'Linux Signal SIGTERM Note', 'Error Codes', 'signal-ref', ['sigterm', 'linux signal 15', 'terminate process']),
    r(325, 'Linux Signal SIGKILL Note', 'Error Codes', 'signal-ref', ['sigkill', 'signal 9', 'kill process']),
    r(326, 'CSS Color aliceblue Reference', 'Web References', 'css-color-ref', ['css named colors', 'aliceblue', 'color names css']),
    r(327, 'HTML Entity &amp; Reference', 'Web References', 'html-entity-ref', ['html entities', 'ampersand entity', 'escape html']),
    r(328, 'IANA Timezone UTC Reference', 'Timezones', 'tz-ref', ['utc timezone', 'iana timezone', 'gmt utc']),
    r(329, 'IANA Timezone America/New_York', 'Timezones', 'tz-ref', ['america new york', 'est edt', 'us east timezone']),
    r(330, 'DNS A Record Reference', 'Web References', 'dns-ref', ['dns a record', 'ipv4 dns', 'dns basics']),
    t(331, 'Time in Tokyo Now', 'City Time', 'tz-city', ['time in tokyo', 'tokyo time now', 'japan time']),
    t(332, 'Time in London Now', 'City Time', 'tz-city', ['time in london', 'london time now', 'uk time']),
    t(333, 'Time in New York Now', 'City Time', 'tz-city', ['time in new york', 'nyc time', 'eastern time']),
    t(334, 'Time in Los Angeles Now', 'City Time', 'tz-city', ['time in los angeles', 'pacific time', 'la time now']),
    t(335, 'Time in Sydney Now', 'City Time', 'tz-city', ['time in sydney', 'australia time', 'sydney clock']),
    t(336, 'Convert EST to UTC', 'TZ Convert', 'tz-convert', ['est to utc', 'eastern to utc', 'timezone convert']),
    t(337, 'Convert PST to UTC', 'TZ Convert', 'tz-convert', ['pst to utc', 'pacific to utc', 'timezone convert']),
    t(338, 'Convert UTC to IST', 'TZ Convert', 'tz-convert', ['utc to ist', 'india time utc', 'timezone convert']),
    t(339, 'DST Start Date Finder (US)', 'DST Tools', 'dst-finder', ['dst date', 'daylight saving', 'us dst 2026']),
    t(340, 'Unix Timestamp in Timezone', 'TZ Convert', 'tz-unix', ['unix timezone', 'epoch local time', 'timestamp tz'])
  ];
}

function batch5() {
  const WEB = 'Web, HTML & CSS';
  const OFF = 'Office & Finance';
  const SEC = 'Privacy & Security';
  const REF = 'Reference & Codes';
  const TIME = 'Date, Time & Timezone';
  const w = (id, name, kind, kw) => row(id, name, WEB, 'CSS Components', kind, kw);
  const o = (id, name, sub, kind, kw) => row(id, name, OFF, sub, kind, kw);
  const sec = (id, name, kind, kw) => row(id, name, SEC, 'Security Tools', kind, kw);
  const r = (id, name, sub, kind, kw) => row(id, name, REF, sub, kind, kw);
  const t = (id, name, sub, kind, kw) => row(id, name, TIME, sub, kind, kw);
  return [
    r(341, 'HTTP 301 Moved Permanently', 'HTTP Status', 'http-ref', ['http 301', 'redirect permanent', 'moved permanently']),
    r(342, 'HTTP 302 Found Redirect', 'HTTP Status', 'http-ref', ['http 302', 'temporary redirect', 'found redirect']),
    r(343, 'HTTP 410 Gone Reference', 'HTTP Status', 'http-ref', ['http 410', 'gone status', 'removed page']),
    r(344, 'Port 8080 Alternative HTTP', 'Ports', 'port-ref', ['port 8080', 'dev server port', 'http alt port']),
    r(345, 'Port 6379 Redis Reference', 'Ports', 'port-ref', ['port 6379', 'redis port', 'cache port']),
    r(346, 'MIME image/png Reference', 'MIME Types', 'mime-ref', ['image png mime', 'png content type', 'mime png']),
    r(347, 'MIME image/webp Reference', 'MIME Types', 'mime-ref', ['image webp', 'webp mime type', 'webp content']),
    r(348, 'Windows Error 5 Access Denied', 'Error Codes', 'win-err-ref', ['windows error 5', 'access denied', 'win32 error']),
    r(349, 'curl error 28 Timeout', 'Error Codes', 'curl-err-ref', ['curl error 28', 'timeout', 'curl failed']),
    r(350, 'CSS Color rebeccapurple Reference', 'Web References', 'css-color-ref', ['rebeccapurple', 'css colors', 'named color']),
    r(351, 'HTML Entity &nbsp; Reference', 'Web References', 'html-entity-ref', ['nbsp entity', 'non breaking space', 'html space']),
    r(352, 'DNS CNAME Record Reference', 'Web References', 'dns-ref', ['cname record', 'dns cname', 'subdomain dns']),
    r(353, 'DNS TXT Record Reference', 'Web References', 'dns-ref', ['txt record', 'dns txt', 'spf txt']),
    r(354, 'HTTP 418 I\'m a teapot', 'HTTP Status', 'http-ref', ['http 418', 'teapot status', 'rfc joke']),
    r(355, 'HTTP 451 Unavailable Legal', 'HTTP Status', 'http-ref', ['http 451', 'legal block', 'unavailable legal']),
    t(356, 'Time in Paris Now', 'City Time', 'tz-city', ['time in paris', 'france time', 'cet time']),
    t(357, 'Time in Berlin Now', 'City Time', 'tz-city', ['time in berlin', 'germany time', 'cet berlin']),
    t(358, 'Time in Dubai Now', 'City Time', 'tz-city', ['time in dubai', 'uae time', 'gulf time']),
    t(359, 'Time in Singapore Now', 'City Time', 'tz-city', ['time in singapore', 'sgt time', 'singapore clock']),
    t(360, 'Time in Mumbai Now', 'City Time', 'tz-city', ['time in mumbai', 'india time ist', 'mumbai clock']),
    t(361, 'Convert GMT to EST', 'TZ Convert', 'tz-convert', ['gmt to est', 'utc to eastern', 'timezone convert']),
    t(362, 'Convert CET to UTC', 'TZ Convert', 'tz-convert', ['cet to utc', 'central europe utc', 'timezone convert']),
    t(363, 'ISO Week Number Calculator', 'Date Tools', 'iso-week', ['iso week number', 'week of year', 'iso 8601 week']),
    t(364, 'Leap Year Checker', 'Date Tools', 'leap-year', ['leap year', 'is leap year', 'february 29']),
    t(365, 'Countdown Days to Date', 'Date Tools', 'countdown-days', ['countdown days', 'days until date', 'event countdown']),
    t(366, 'Business Hours Overlap (2 zones)', 'DST Tools', 'biz-hours', ['business hours overlap', 'meeting time zones', 'schedule overlap']),
    t(367, 'Age on a Specific Date', 'Date Tools', 'age-on-date', ['age on date', 'birthday on date', 'how old on']),
    t(368, 'Julian Day Number Calculator', 'Date Tools', 'julian-day', ['julian day', 'julian date', 'astronomy julian']),
    t(369, 'Weekday Name from Date', 'Date Tools', 'weekday-name', ['day of week', 'weekday from date', 'what day is']),
    t(370, 'Add Business Days', 'Date Tools', 'workdays-calc', ['add business days', 'weekdays add', 'business date']),
    w(371, 'CSS Button Component Generator', 'button-css', ['css button', 'button styles', 'cta button css']),
    w(372, 'CSS Card Layout Generator', 'card-css', ['css card', 'card layout', 'ui card css']),
    w(373, 'CSS Form Field Styles', 'form-css', ['css form', 'input styles', 'form field css']),
    w(374, 'CSS Responsive Table', 'table-css', ['responsive table css', 'table scroll', 'data table css']),
    w(375, 'Skip to Content Link HTML', 'a11y-html', ['skip link', 'skip to content', 'accessibility link']),
    w(376, 'ARIA Label Snippet Generator', 'a11y-html', ['aria label', 'aria-labelledby', 'accessibility aria']),
    w(377, 'Landmark Roles HTML Guide', 'a11y-html', ['landmark roles', 'main nav aside', 'html landmarks']),
    w(378, 'Focus Visible CSS Ring', 'a11y-html', ['focus visible', 'focus ring css', 'keyboard focus']),
    w(379, 'Reduced Motion CSS', 'a11y-html', ['prefers reduced motion', 'motion safe', 'accessibility motion']),
    w(380, 'Print Stylesheet Starter', 'print-css', ['print css', 'print stylesheet', '@media print']),
    w(381, 'CSS Container Query Snippet', 'container-css', ['container queries', 'css container', '@container']),
    w(382, 'CSS Variables Theme Starter', 'theme-css', ['css variables theme', 'dark mode variables', 'design tokens css']),
    w(383, 'Dark Mode Toggle CSS', 'dark-mode-css', ['dark mode css', 'color scheme', 'theme toggle css']),
    w(384, 'Tooltip CSS Generator', 'tooltip-css', ['css tooltip', 'hover tooltip', 'title tooltip css']),
    w(385, 'Modal Dialog CSS', 'modal-css', ['css modal', 'dialog overlay', 'popup css']),
    w(386, 'Accordion CSS Pattern', 'accordion-css', ['css accordion', 'collapse panel', 'faq accordion css']),
    w(387, 'Tabs Component CSS', 'tabs-css', ['css tabs', 'tab panel', 'ui tabs css']),
    w(388, 'Breadcrumb HTML/CSS', 'breadcrumb-html', ['breadcrumb html', 'breadcrumb css', 'nav breadcrumb']),
    w(389, 'Pagination CSS Component', 'pagination-css', ['pagination css', 'page numbers css', 'pager styles']),
    w(390, 'Alert Banner CSS', 'alert-css', ['alert css', 'banner message', 'notification css']),
    o(391, 'Invoice Line Total Calculator', 'Finance', 'invoice-lines', ['invoice calculator', 'line total', 'invoice math']),
    o(392, 'Hourly to Salary Converter', 'Finance', 'hourly-salary', ['hourly to salary', 'annual salary hourly', 'wage convert']),
    o(393, 'Overtime Pay Estimator', 'Finance', 'overtime-calc', ['overtime pay', 'overtime calculator', 'time and half']),
    o(394, 'Break-even Units Calculator', 'Finance', 'breakeven-calc', ['break even', 'breakeven units', 'fixed cost']),
    o(395, 'Inventory Turnover Ratio', 'Finance', 'inventory-turn', ['inventory turnover', 'stock turnover', 'cogs inventory']),
    o(396, 'Simple Amortization Schedule', 'Finance', 'amort-schedule', ['amortization schedule', 'loan schedule', 'payment table']),
    o(397, 'Sales Tax Add Calculator', 'Finance', 'sales-tax', ['sales tax calculator', 'add tax price', 'tax inclusive']),
    o(398, 'Margin vs Markup Compare', 'Finance', 'margin-markup', ['margin vs markup', 'markup margin', 'pricing math']),
    o(399, 'Freelance Rate Calculator', 'Finance', 'freelance-rate', ['freelance rate', 'hourly rate freelance', 'billable rate']),
    o(400, 'Rent vs Buy Monthly Compare', 'Finance', 'rent-buy', ['rent vs buy', 'housing compare', 'mortgage vs rent']),
    o(401, 'Quote Line Item Builder', 'Finance', 'quote-lines', ['quote builder', 'line items quote', 'estimate lines']),
    o(402, 'Timesheet Hours Summarizer', 'Finance', 'timesheet-sum', ['timesheet total', 'hours sum', 'weekly hours']),
    o(403, 'Commission Calculator', 'Finance', 'commission-calc', ['commission calculator', 'sales commission', 'percent commission']),
    o(404, 'ROI Calculator Simple', 'Finance', 'roi-calc', ['roi calculator', 'return on investment', 'investment roi']),
    o(405, 'Currency Format Locale Table', 'Finance', 'currency-format', ['currency format', 'locale money', 'number format money']),
    sec(406, 'OTP Length Strength Guide', 'otp-guide', ['otp length', 'one time password', '2fa otp']),
    sec(407, 'PIN Strength Checker', 'pin-strength', ['pin strength', 'numeric pin', 'secure pin']),
    sec(408, 'PGP Armor Block Parser', 'pgp-parse', ['pgp armor', 'pgp message', 'openpgp armor']),
    sec(409, 'JWT vs Session Note', 'jwt-session-note', ['jwt vs session', 'token session', 'auth comparison']),
    sec(410, 'Password Entropy Explainer', 'entropy-note', ['password entropy', 'bits entropy', 'strong password math']),
    sec(411, 'TOTP Setup Checklist', 'totp-checklist', ['totp setup', 'authenticator app', '2fa checklist']),
    sec(412, 'API Key Rotation Checklist', 'apikey-checklist', ['api key rotation', 'rotate secrets', 'key hygiene']),
    sec(413, 'CSP Report-Only Template', 'csp-report', ['csp report-only', 'content security policy', 'csp header']),
    sec(414, 'Subresource Integrity Generator', 'sri-gen', ['sri hash', 'integrity attribute', 'cdn sri']),
    sec(415, 'Security Headers Mini Audit', 'sec-headers', ['security headers audit', 'header checklist', 'owasp headers']),
    sec(416, 'CSRF Token Pattern Note', 'csrf-note', ['csrf token', 'cross site request', 'csrf protection']),
    sec(417, 'SameSite Cookie Guide', 'samesite-note', ['samesite cookie', 'cookie lax strict', 'csrf cookie']),
    sec(418, 'OAuth Scope Checklist', 'oauth-checklist', ['oauth scopes', 'openid scope', 'oauth consent']),
    sec(419, 'Rate Limit Header Template', 'rate-limit-hdr', ['rate limit headers', 'retry-after', 'x-ratelimit']),
    sec(420, 'Secrets in .env Lint', 'env-lint', ['env secrets', 'dotenv security', 'leak env'])
  ];
}

function batch6() {
  const DES = 'Design & Color';
  const INT = 'Integrations & Scenarios';
  const PDF = 'PDF & Documents';
  const PROD = 'Productivity & Career';
  const d = (id, name, kind, kw) => row(id, name, DES, 'Color & UI', kind, kw);
  const i = (id, name, kind, kw) => row(id, name, INT, 'Workflows', kind, kw);
  const p = (id, name, sub, kind, kw) => row(id, name, PDF, sub, kind, kw);
  const pr = (id, name, kind, kw) => row(id, name, PROD, 'Career', kind, kw);
  const items = [
    d(421, 'Palette from Hex List', 'palette-gen', ['color palette', 'hex palette', 'color scheme']),
    d(422, 'WCAG Contrast Ratio Calculator', 'contrast-ratio', ['contrast ratio', 'wcag contrast', 'aa aaa contrast']),
    d(423, 'Glassmorphism CSS Generator', 'glass-css', ['glassmorphism', 'frosted glass css', 'blur card']),
    d(424, 'Neumorphism Shadow CSS', 'neu-css', ['neumorphism', 'soft ui css', 'neomorphic button']),
    d(425, 'Color Scale Generator (tints)', 'color-scale', ['color scale', 'tints shades', 'primary scale']),
    d(426, 'HSL Adjustment Explainer', 'hsl-note', ['hsl color', 'hue saturation', 'adjust hsl']),
    d(427, 'OKLCH Color Note', 'oklch-note', ['oklch css', 'perceptual color', 'modern css color']),
    d(428, 'Figma to CSS Spacing Map', 'figma-spacing', ['figma spacing', 'design tokens', 'spacing scale']),
    d(429, 'Icon Size Scale Reference', 'icon-scale', ['icon sizes', 'icon 16 24 32', 'ui icon scale']),
    d(430, 'Typography Scale Calculator', 'type-scale', ['type scale', 'font size scale', 'modular scale']),
    i(431, 'CSV Clean then JSON Workflow', 'workflow-steps', ['csv to json workflow', 'clean csv json', 'data pipeline']),
    i(432, 'UTM Build then Length Check', 'workflow-steps', ['utm workflow', 'campaign url check', 'utm seo']),
    i(433, 'JSON Format then Schema Workflow', 'workflow-steps', ['json schema workflow', 'format json schema', 'api workflow']),
    i(434, 'SEO Meta then SERP Preview Flow', 'workflow-steps', ['meta serp workflow', 'seo preview flow', 'snippet check']),
    i(435, 'Log Redact then Share Workflow', 'workflow-steps', ['log redaction workflow', 'mask pii logs', 'safe log share']),
    i(436, 'Cron Explain then Schedule Flow', 'workflow-steps', ['cron workflow', 'schedule explain', 'devops cron']),
    i(437, 'Image Rename then Alt Text Flow', 'workflow-steps', ['image seo workflow', 'filename alt text', 'image publish']),
    i(438, 'Sitemap then robots.txt Flow', 'workflow-steps', ['sitemap robots workflow', 'launch seo files', 'indexing setup']),
    i(439, 'Password Gen then Strength Flow', 'workflow-steps', ['password workflow', 'generate strong password', 'credential setup']),
    i(440, 'Deploy Checklist for Tool Pages', 'workflow-steps', ['tool deploy checklist', 'launch tool site', 'pages deploy']),
    p(441, 'PDF Scan DPI Planner', 'Scan & Print', 'pdf-scan-dpi', ['scan dpi', 'pdf scan settings', 'document scan']),
    p(442, 'PDF Duplex Print Planner', 'Scan & Print', 'pdf-duplex', ['duplex print', 'double sided pdf', 'print planner']),
    p(443, 'PDF Cover Page Template', 'Templates', 'pdf-cover', ['pdf cover page', 'report cover', 'title page pdf']),
    p(444, 'PDF Table of Contents Planner', 'Templates', 'pdf-toc-plan', ['pdf toc', 'table of contents pdf', 'chapter pdf']),
    p(445, 'PDF Redaction Planner', 'Privacy', 'pdf-redact-plan', ['pdf redaction', 'blackout pdf', 'remove sensitive pdf']),
    p(446, 'PDF Compare Text Plan', 'PDF Tools', 'pdf-compare-plan', ['compare pdf text', 'pdf diff plan', 'document compare']),
    p(447, 'PDF Watermark Planner', 'PDF Tools', 'pdf-watermark-plan', ['pdf watermark plan', 'stamp pdf', 'diagonal watermark']),
    p(448, 'PDF Print Marks Planner', 'Scan & Print', 'pdf-print-marks', ['crop marks pdf', 'print marks', 'trim marks']),
    p(449, 'PDF Preflight Checklist', 'PDF Tools', 'pdf-preflight', ['pdf preflight', 'print ready pdf', 'preflight check']),
    p(450, 'PDF Office Convert Plan', 'PDF Tools', 'pdf-office-plan', ['pdf to docx plan', 'office pdf convert', 'word pdf']),
    pr(451, 'Cover Letter Outline Builder', 'cover-letter', ['cover letter outline', 'job application letter', 'cover letter template']),
    pr(452, 'LinkedIn Headline Ideas', 'linkedin-headline', ['linkedin headline', 'profile headline', 'professional headline']),
    pr(453, 'Meeting Agenda Template', 'agenda-template', ['meeting agenda', 'agenda template', 'standup agenda']),
    pr(454, 'OKR Statement Formatter', 'okr-format', ['okr template', 'objectives key results', 'okr format']),
    pr(455, 'Weekly Plan Template', 'weekly-plan', ['weekly plan', 'week planner template', 'productivity plan']),
    row(456, 'JSON API Mock Response Builder', 'Development & Data', 'API Tools', 'mock-json', ['mock json api', 'sample api response', 'fake json api']),
    row(457, 'REST Status Pick for UI', 'Development & Data', 'API Tools', 'ui-status-pick', ['http status ui', 'error code ui', 'status badge']),
    row(458, 'Email Signature HTML Generator', 'Content & Writing', 'Email Tools', 'email-sig', ['email signature html', 'signature generator', 'professional signature']),
    pr(459, 'Newsletter Outline from Topics', 'outline-gen', ['newsletter outline', 'email newsletter plan', 'content newsletter']),
    pr(460, 'Changelog Entry Formatter', 'changelog-fmt', ['changelog format', 'release notes', 'keep a changelog']),
    row(461, 'Base64 Decode Text', 'Development & Data', 'Encoding', 'b64-text', ['base64 decode', 'decode base64', 'base64 text']),
    row(462, 'Hex Decode Text', 'Development & Data', 'Encoding', 'hex-decode', ['hex decode', 'hex to text', 'decode hex']),
    row(463, 'ROT13 Encoder', 'Development & Data', 'Encoding', 'rot13', ['rot13', 'rotate 13', 'cipher rot13']),
    row(464, 'Caesar Cipher Tool', 'Development & Data', 'Encoding', 'caesar', ['caesar cipher', 'shift cipher', 'encode caesar']),
    row(465, 'Text Columns to Rows', 'Office & Spreadsheets', 'Text Cleanup', 'cols-to-rows', ['columns to rows', 'transpose text', 'split columns']),
    row(466, 'Rows to CSV from Paste', 'Office & Spreadsheets', 'CSV & Tables', 'paste-csv', ['paste to csv', 'table paste csv', 'tsv paste']),
    row(467, 'List Intersection Tool', 'Office & Spreadsheets', 'List Tools', 'list-intersect', ['list intersection', 'common items two lists', 'compare lists']),
    row(468, 'List Difference Tool', 'Office & Spreadsheets', 'List Tools', 'list-diff', ['list difference', 'items in a not b', 'list compare']),
    row(469, 'Weighted Average Calculator', 'Calculators & Units', 'Math & Units', 'weighted-avg', ['weighted average', 'weight mean', 'average weights']),
    row(470, 'Quadratic Equation Solver', 'Calculators & Units', 'Math & Units', 'quadratic', ['quadratic solver', 'solve quadratic', 'ax2 bx c']),
    row(471, 'Permutation nPr Calculator', 'Calculators & Units', 'Math & Units', 'npr-calc', ['permutation calculator', 'npr math', 'combinatorics']),
    row(472, 'Combination nCr Calculator', 'Calculators & Units', 'Math & Units', 'ncr-calc', ['combination calculator', 'ncr math', 'choose r']),
    row(473, 'Prime Number Checker', 'Calculators & Units', 'Math & Units', 'prime-check', ['prime checker', 'is prime', 'prime number']),
    row(474, 'Fibonacci Sequence Generator', 'Calculators & Units', 'Math & Units', 'fibonacci', ['fibonacci generator', 'fib sequence', 'fib numbers']),
    row(475, 'Matrix 2x2 Multiply', 'Calculators & Units', 'Math & Units', 'matrix-2x2', ['matrix multiply', '2x2 matrix', 'linear algebra']),
    row(476, 'Angle Degrees Radians Convert', 'Calculators & Units', 'Math & Units', 'angle-convert', ['degrees radians', 'angle convert', 'deg to rad']),
    row(477, 'Fuel Efficiency L/100km', 'Calculators & Units', 'Math & Units', 'fuel-efficiency', ['fuel efficiency', 'l per 100km', 'consumption calculator']),
    row(478, 'Wind Chill Estimator', 'Calculators & Units', 'Math & Units', 'wind-chill', ['wind chill', 'feels like temperature', 'cold wind']),
    row(479, 'Heat Index Estimator', 'Calculators & Units', 'Math & Units', 'heat-index', ['heat index', 'humidity temperature', 'feels hot']),
    row(480, 'Roman Date Converter Note', 'Date, Time & Timezone', 'Date Tools', 'roman-date', ['roman numerals date', 'date roman', 'fancy date']),
    row(481, 'QR Code Content Planner', 'Design & Frontend', 'Image Tools', 'qr-plan', ['qr code content', 'qr url plan', 'qr generator plan']),
    row(482, 'UTM Campaign Calendar Template', 'SEO & Webmasters', 'Campaign Tracking', 'utm-calendar', ['utm calendar', 'campaign schedule', 'marketing calendar utm']),
    row(483, 'robots.txt Block AI Bots Template', 'SEO & Webmasters', 'Technical SEO', 'robots-ai', ['block ai bots', 'robots gptbot', 'crawler robots']),
    row(484, 'IndexNow URL Submit Template', 'SEO & Webmasters', 'Technical SEO', 'indexnow', ['indexnow', 'bing indexnow', 'instant indexing']),
    row(485, 'Core Web Vitals Field Checklist', 'SEO & Webmasters', 'Technical SEO', 'cwv-checklist', ['core web vitals', 'lcp cls inp', 'pagespeed checklist']),
    row(486, 'Lighthouse CI Config Snippet', 'Development & Data', 'Performance', 'lhci-snippet', ['lighthouse ci', 'lhci config', 'performance ci']),
    row(487, 'Service Worker Cache Versioning', 'Development & Data', 'PWA', 'sw-cache', ['service worker cache', 'cache versioning', 'pwa cache']),
    row(488, 'Web App Manifest Starter', 'Development & Data', 'PWA', 'manifest-gen', ['web app manifest', 'pwa manifest', 'manifest json']),
    row(489, 'Apple Touch Icon Sizes List', 'Design & Frontend', 'Image Tools', 'touch-icon', ['apple touch icon', 'ios icon sizes', 'home screen icon']),
    row(490, 'Security.txt Generator', 'Privacy & Security', 'Security Tools', 'security-txt', ['security.txt', 'responsible disclosure', 'security contact']),
    row(491, 'humans.txt Generator', 'Content & Writing', 'Site Meta', 'humans-txt', ['humans txt', 'site credits', 'team humans']),
    row(492, 'license-snippet SPDX Picker', 'Development & Data', 'Open Source', 'spdx-license', ['spdx license', 'open source license', 'license identifier']),
    row(493, 'Changelog Semver Bump Guide', 'Development & Data', 'Release', 'semver-bump', ['semver bump', 'version bump', 'release version']),
    row(494, 'Git Conventional Commit Format', 'Development & Data', 'Git', 'conventional-commit', ['conventional commits', 'commit message format', 'semantic commit']),
    row(495, 'API Pagination Cursor Template', 'Development & Data', 'API Tools', 'api-pagination', ['cursor pagination', 'api next page', 'pagination token']),
    row(496, 'Webhook Payload Idempotency Key', 'Development & Data', 'API Tools', 'idempotency-key', ['idempotency key', 'webhook dedupe', 'retry idempotent']),
    row(497, 'HTML Email Inline CSS Tips', 'Content & Writing', 'Email', 'email-html', ['html email css', 'inline css email', 'newsletter html']),
    row(498, 'Markdown Email Export', 'Content & Writing', 'Email', 'md-email', ['markdown email', 'md to email html', 'email markdown']),
    row(499, 'Bulk Sitemap URL Validator', 'SEO & Webmasters', 'Technical SEO', 'sitemap-validate', ['validate sitemap urls', 'sitemap checker', 'url list validate']),
    row(500, 'AIHH Tool Launch SEO Checklist', 'SEO & Webmasters', 'Technical SEO', 'launch-checklist', ['tool launch seo', 'new tool checklist', 'go live seo'])
  ];
  return items;
}

function buildCatalog101to500() {
  return [...batch2(), ...batch3(), ...batch4(), ...batch5(), ...batch6()];
}

module.exports = { buildCatalog101to500 };
