const fs = require('fs');
const path = require('path');

const file = path.join(__dirname, '..', 'private', 'admin.html');
let s = fs.readFileSync(file, 'utf8');

s = s.replace('lang="zh-CN"', 'lang="en"');

const pairs = [
  ['AIHH.ai 后台管理', 'AIHH.ai Admin'],
  ['隐藏后台地址 + 登录鉴权 + TXT 文本库管理 + SEO/导航一体化配置', 'Hidden admin URL · login auth · TXT storage · SEO & navigation'],
  ['TXT 数据库', 'TXT storage'],
  ['二级分类可配', 'Subcategories'],
  ['SEO 可控', 'SEO controls'],
  ['登录后台', 'Sign in'],
  ['只有知道后台隐藏地址并输入正确账号密码，才能进入管理台。', 'You need the secret admin URL and valid credentials to open the dashboard.'],
  ['账号', 'Username'],
  ['请输入后台账号', 'Admin username'],
  ['密码', 'Password'],
  ['请输入后台密码', 'Admin password'],
  ['登录进入后台', 'Sign in'],
  ['账号：', 'User: '],
  ['后台地址：', 'Admin path: '],
  ['数据文件：`storage/site-data.txt` + `storage/admin-config.txt`', 'Data: `storage/site-data.txt` + `storage/admin-config.txt`'],
  ['这里能管理导航站的登录安全、SEO 文案、一级分类、二级分类和上架工具数据。', 'Manage login security, SEO copy, categories, subcategories, and published tools.'],
  ['刷新数据', 'Refresh'],
  ['退出登录', 'Sign out'],
  ['工具管理', 'Tools'],
  ['类目管理', 'Categories'],
  ['广告 / 通知', 'Ads / notices'],
  ['SEO 设置', 'SEO'],
  ['安全设置', 'Security'],
  ['后台按“列表 + 搜索 + 筛选 + 批量 + 分页”组织，避免无限下拉。', 'List + search + filters + batch actions + pagination—no endless dropdowns.'],
  ['支持搜索、筛选、分页、批量操作；修改后记得点击“保存工具变更”。', 'Search, filter, paginate, and batch-edit—then click Save tool changes.'],
  ['全选当前页', 'Select page'],
  ['清空选择', 'Clear selection'],
  ['保存工具变更', 'Save tool changes'],
  ['搜索（名称/描述/标签/关键词/URL）', 'Search (name, description, tag, keywords, URL)'],
  ['例如：PPT、SEO、JSON、简历、pdf2word...', 'e.g. JSON, JWT, SEO, CSV, cron...'],
  ['一级类目筛选', 'Main category'],
  ['二级类目筛选', 'Subcategory'],
  ['批量操作（对已勾选生效）', 'Batch actions (selected rows)'],
  ['设为精选', 'Feature'],
  ['取消精选', 'Unfeature'],
  ['上架', 'Enable'],
  ['下架', 'Disable'],
  ['批量删除', 'Delete selected'],
  ['工具列表', 'Tool list'],
  ['工具', 'Tool'],
  ['类目', 'Category'],
  ['标签', 'Tag'],
  ['状态', 'Status'],
  ['操作', 'Actions'],
  ['编辑工具', 'Edit tool'],
  ['取消', 'Cancel'],
  ['保存到列表', 'Apply to list'],
  ['工具名称', 'Tool name'],
  ['工具链接', 'Tool URL'],
  ['SEO 标签', 'SEO tag'],
  ['工具描述', 'Description'],
  ['SEO 关键词', 'SEO keywords'],
  ['设为首页精选推荐', 'Featured on homepage'],
  ['上架（前台可见）', 'Published (visible on site)'],
  ['一级类目', 'Main category'],
  ['二级类目', 'Subcategory'],
  ['提示：这里保存只是更新到当前列表与数据结构，仍需点击上方“保存工具变更”才会写入文件。', 'Tip: Apply updates the in-memory list only—click Save tool changes above to write to disk.'],
  ['管理一级/二级类目结构；工具的具体内容建议在“工具管理”里批量维护。', 'Edit main/subcategory structure; maintain tool details under Tools.'],
  ['新增一级分类', 'Add main category'],
  ['保存类目结构', 'Save categories'],
  ['支持文字走马灯公告（多条循环）与多个轮播位（可选位置）。', 'Ticker announcements and optional carousel slots.'],
  ['保存广告/通知', 'Save ads / notices'],
  ['走马灯公告', 'Ticker announcements'],
  ['新增公告', 'Add announcement'],
  ['轮播位', 'Carousel slot'],
  ['新增轮播位', 'Add carousel'],
  ['首页每页数量', 'Tools per page'],
  ['默认 12；前台会做分页展示，避免无限滚动。', 'Default 12; the homepage paginates instead of infinite scroll.'],
  ['这里决定首页标题、描述、关键词、英雄区文案和底部长文内容。', 'Homepage title, description, keywords, hero copy, and footer articles.'],
  ['站点名称', 'Site name'],
  ['页面标题 Title', 'Page title'],
  ['Meta 关键词', 'Meta keywords'],
  ['Meta 描述', 'Meta description'],
  ['英雄区徽标文案', 'Hero badge'],
  ['英雄区主标题前半段', 'Hero title (first line)'],
  ['英雄区高亮标题', 'Hero highlight'],
  ['英雄区描述', 'Hero description'],
  ['顶部统计说明文案', 'Matrix description'],
  ['英雄区标签（每行一个）', 'Hero tags (one per line)'],
  ['一级分类标题', 'Main category title'],
  ['二级分类标题', 'Subcategory title'],
  ['结果面板标题', 'Results panel title'],
  ['一级分类说明', 'Main category description'],
  ['高频入口说明', 'Recommended section description'],
  ['全部视图下的二级分类说明', 'Subcategory description (all view)'],
  ['已选主类后的二级分类说明', 'Subcategory description (filtered)'],
  ['结果面板上方小标题', 'Results eyebrow'],
  ['推荐模块上方小标题', 'Recommended eyebrow'],
  ['推荐模块标题', 'Recommended title'],
  ['结果面板文案模板（用 {count} 表示数量）', 'Results template (use {count})'],
  ['空结果提示', 'Empty state message'],
  ['页脚文案', 'Footer text'],
  ['SEO 长文区块', 'SEO article blocks'],
  ['建议写自然流、场景化、非硬堆关键词内容。', 'Write natural, scenario-based copy—not keyword stuffing.'],
  ['新增文章区块', 'Add article block'],
  ['保存 SEO 设置', 'Save SEO settings'],
  ['后台安全设置', 'Admin security'],
  ['复杂后台地址只是第一层，真正的保护是账号密码和会话登录。', 'A long secret URL helps, but credentials and session auth are what protect the admin.'],
  ['当前后台隐藏地址', 'Current admin path'],
  ['建议使用较长、无规律的地址字符串，避免被轻易枚举。', 'Use a long, random path string to reduce guessing.'],
  ['保存后台地址', 'Save admin path'],
  ['生成复杂地址', 'Generate random path'],
  ['当前密码', 'Current password'],
  ['修改前必须输入当前密码', 'Required to change credentials'],
  ['新账号', 'New username'],
  ['新的后台账号', 'New admin username'],
  ['新密码', 'New password'],
  ['新的后台密码', 'New admin password'],
  ['保存账号密码', 'Save credentials'],
  ['请求失败', 'Request failed'],
  ['文章区块', 'Article block'],
  ['删除区块', 'Remove block'],
  ['标题', 'Title'],
  ['内容', 'Content'],
  ['一级分类', 'Main category'],
  ['新增二级分类', 'Add subcategory'],
  ['删除一级分类', 'Delete main category'],
  ['一级分类名称', 'Main category name'],
  ['一级分类 ID', 'Main category ID'],
  ['二级分类', 'Subcategory'],
  ['删除二级分类', 'Delete subcategory'],
  ['二级分类名称', 'Subcategory name'],
  ['二级分类 ID', 'Subcategory ID'],
  ['删除工具', 'Delete tool'],
  ['新的 SEO 区块标题', 'New SEO article title'],
  ['这里填写适合自然流 SEO 的正文内容。', 'Write natural SEO body copy here.'],
  ['新的一级分类', 'New main category'],
  ['确定删除这个一级分类吗？', 'Delete this main category?'],
  ['新的二级分类', 'New subcategory'],
  ['确定删除这个二级分类吗？', 'Delete this subcategory?'],
  ['新工具', 'New tool'],
  ['这里填写工具描述', 'Tool description here'],
  ['SEO标签', 'SEO tag'],
  ['确定删除这个工具吗？', 'Delete this tool?'],
  ['导航数据已保存', 'Navigation data saved'],
  ['全部一级类目', 'All main categories'],
  ['全部二级类目', 'All subcategories'],
  ['第 ', 'Page '],
  [' / ', ' / '],
  [' 页 · 共 ', ' · '],
  [' 条', ' items'],
  ['上一页', 'Previous'],
  ['下一页', 'Next'],
  ['当前匹配 ', 'Showing '],
  [' · 已勾选 ', ' · selected '],
  ['请先勾选要批量操作的工具', 'Select tools first'],
  ['已批量设为精选（未写入文件）', 'Batch featured (not saved yet)'],
  ['已批量取消精选（未写入文件）', 'Batch unfeatured (not saved yet)'],
  ['已批量上架（未写入文件）', 'Batch enabled (not saved yet)'],
  ['已批量下架（未写入文件）', 'Batch disabled (not saved yet)'],
  ['请先勾选要批量删除的工具', 'Select tools to delete'],
  ['确定删除已勾选的 ', 'Delete '],
  [' 个工具吗？此操作不可恢复。', ' selected tools? This cannot be undone.'],
  ['已批量删除（未写入文件）', 'Batch deleted (not saved yet)'],
  ['确定删除工具「', 'Delete tool “'],
  ['」吗？', '”?'],
  ['编辑', 'Edit'],
  ['删除', 'Delete'],
  [' · 精选', ' · featured'],
  ['工具名称和链接不能为空', 'Tool name and URL are required'],
  ['目标类目不存在，请先在类目管理里创建', 'Target category not found—create it under Categories'],
  ['已更新工具（未写入文件）', 'Tool updated (not saved yet)'],
  ['暂无公告，点击“新增公告”添加。', 'No announcements—click Add announcement.'],
  ['公告', 'Announcement'],
  ['文案', 'Text'],
  ['排序（小在前）', 'Sort order (ascending)'],
  ['链接（可选）', 'Link (optional)'],
  ['启用', 'Enabled'],
  ['新的公告：这里填写走马灯文案', 'New announcement ticker text'],
  ['暂无轮播位，点击“新增轮播位”创建。', 'No carousels—click Add carousel.'],
  ['新增轮播项', 'Add slide'],
  ['删除轮播位', 'Delete carousel'],
  ['轮播位名称', 'Carousel name'],
  ['位置', 'Position'],
  ['工具列表上方', 'Above tool list'],
  ['首屏/英雄区下方', 'Below hero'],
  ['页面底部', 'Page bottom'],
  ['启用该轮播位', 'Enable carousel'],
  ['轮播项', 'Slide'],
  ['描述（可选）', 'Description (optional)'],
  ['图片 URL（可选）', 'Image URL (optional)'],
  ['新的轮播位', 'New carousel'],
  ['确定删除这个轮播位吗？', 'Delete this carousel?'],
  ['新的轮播内容', 'New slide title'],
  ['广告/通知配置已保存', 'Ads / notices saved'],
  ['后台地址已更新，请记住新地址', 'Admin path updated—save the new URL'],
  ['已退出登录', 'Signed out'],
  ['登录成功', 'Signed in'],
  ['账号密码已更新', 'Credentials updated'],
  ['SEO 设置已保存', 'SEO settings saved'],
  ['保存类目结构', 'Save categories'],
  ['保存前台展示配置', 'Save homepage UI'],
  ['前台展示配置已保存', 'Homepage UI saved'],
];

for (const [from, to] of pairs) {
  s = s.split(from).join(to);
}

fs.writeFileSync(file, s, 'utf8');
console.log('englishize-admin.js done');
