const fs = require('fs');
const path = require('path');

const file = path.join(__dirname, 'tool-runtime.js');
let s = fs.readFileSync(file, 'utf8');

const pairs = [
  ["return '列名: '", "return 'Columns: '"],
  ["'\\n行数: '", "'\\nData rows: '"],
  ["'\\n\\n去重后:\\n'", "'\\n\\nDeduped lines:\\n'"],
  ["return '仅左侧:\\n'", "return 'Left only:\\n'"],
  ["'\\n\\n仅右侧:\\n'", "'\\n\\nRight only:\\n'"],
  ["'格式有效'", "'valid format'"],
  ["'格式异常'", "'invalid format'"],
  ['200: \'OK 成功\'', '200: \'OK\''],
  ['301: \'永久重定向\'', '301: \'Moved Permanently\''],
  ['302: \'临时重定向\'', '302: \'Found\''],
  ['400: \'请求错误\'', '400: \'Bad Request\''],
  ['401: \'未授权\'', '401: \'Unauthorized\''],
  ['403: \'禁止访问\'', '403: \'Forbidden\''],
  ['404: \'未找到\'', '404: \'Not Found\''],
  ['409: \'资源冲突\'', '409: \'Conflict\''],
  ['422: \'语义校验失败\'', '422: \'Unprocessable Entity\''],
  ['429: \'请求过多\'', '429: \'Too Many Requests\''],
  ['500: \'服务器错误\'', '500: \'Internal Server Error\''],
  ['502: \'网关错误\'', '502: \'Bad Gateway\''],
  ['503: \'服务不可用\'', '503: \'Service Unavailable\''],
  ["'可在 RFC HTTP 状态码表中进一步确认'", "'See RFC 9110 for details'"],
  ["return 'Title 字符数: '", "return 'Title length: '"],
  ["'，建议 20-60\\nDescription 字符数: '", "' (suggested 20–60)\\nDescription length: '"],
  ["'，建议 70-160'", "' (suggested 70–160)'"],
  ['预览建议：标题放核心关键词，描述说明输入、输出和使用场景。', 'Tip: put primary keywords in the title; describe input, output, and use case in the description.'],
  ["if (kind === 'intent') return lines(text).map((k) => k + ' -> ' + (/buy|price|购买|下载/.test(k) ? '交易型' : /login|官网|aihh/.test(k) ? '导航型' : /best|how|教程|是什么/.test(k) ? '信息型' : '工具/混合型')).join('\\n');",
    "if (kind === 'intent') return lines(text).map((k) => k + ' -> ' + (/buy|price|download/i.test(k) ? 'Transactional' : /login|official|aihh/i.test(k) ? 'Navigational' : /best|how|tutorial|what is/i.test(k) ? 'Informational' : 'Tool / mixed')).join('\\n');"],
  ["'\\n\\nH1 数量: '", "'\\n\\nH1 count: '"],
  ["'\\n图片缺 alt: '", "'\\nImages missing alt: '"],
  ["return '目录:\\n'", "return 'Table of contents:\\n'"],
  ["'\\n\\n纯文本预览:\\n'", "'\\n\\nPlain text preview:\\n'"],
  ["return '字符数: '", "return 'Characters: '"],
  ["'\\n中文字符: '", "'\\nCJK characters: '"],
  ["'\\n英文单词: '", "'\\nEnglish words: '"],
  ["'\\n估算阅读时间: '", "'\\nEstimated reading time: '"],
  ["' 分钟'", "' min'"],
  ["return '含税金额: '", "return 'Gross amount: '"],
  ["'\\n税率: '", "'\\nTax rate: '"],
  ["'\\n不含税: '", "'\\nNet amount: '"],
  ["'\\n税额: '", "'\\nTax amount: '"],
  ["config.name || '本站'", "config.name || 'This site'"],
  ["return site + ' 使用说明\\n\\n本工具用于'", "return site + ' — Usage\\n\\nThis tool helps with '"],
  ["(config.keywords || []).join('、')", "(config.keywords || []).join(', ')"],
  ["'等场景。输入内容仅在浏览器本地处理，不会主动上传到服务器。建议不要在公共电脑处理高度敏感信息。\\n\\n联系邮箱：'", "' scenarios. Input is processed locally in your browser and is not uploaded. Avoid highly sensitive data on shared computers.\\n\\nContact: '"],
  ["return '网络: '", "return 'Network: '"],
  ["'\\n可用主机数(约): '", "'\\nApprox. usable hosts: '"],
  ["'\\n掩码(粗算): '", "'\\nMask (approx.): '"],
  ["throw new Error('请输入 #hex 或 rgb(r,g,b)')", "throw new Error('Enter #hex or rgb(r,g,b)')"],
  ["return '宽高: '", "return 'Dimensions: '"],
  ["'\\n最简比例: '", "'\\nReduced ratio: '"],
  ["'\\n小数比例: '", "'\\nDecimal ratio: '"],
  ["return '未找到有效 viewBox'", "return 'No valid viewBox found'"],
  ["'\\n逻辑宽: '", "'\\nLogical width: '"],
  ["'\\n逻辑高: '", "'\\nLogical height: '"],
  ["'\\n宽高比: '", "'\\nAspect ratio: '"],
  ['if (/免费|在线|工具|JSON|SEO/i.test(t)) score += 10;', 'if (/free|online|tool|json|seo/i.test(t)) score += 10;'],
  ["return t + ' -> 评分 '", "return t + ' -> score '"],
  ["return '【标题】'", "return 'Title: '"],
  ["(kv.product || '好物分享') + '真实体验", "(kv.product || 'Product') + ' — real experience"],
  ["【开头钩子】3 秒说明痛点", "Hook: state the pain in 3 seconds"],
  ["【正文结构】", "Body:"],
  ["1. 使用场景", "1. Use case"],
  ["2. 真实优点（", "2. Key benefit ("],
  ["）\\n3. 注意事项", ")\\n3. Caveats"],
  ["【结尾】适合 ", "Close: fits "],
  ["' 收藏备用'", "' — save for later'"],
  ["return '| 镜号 | 画面 | 口播 |", "return '| # | Visual | Script |"],
  ["| 1 | 问题特写 | 你是不是也在找 ", "| 1 | Problem | Still looking for "],
  ["？ |\\n| 2 | 屏幕录制 | 打开工具，粘贴内容 |\\n| 3 | 结果展示 | 一键得到结果并复制 |\\n| 4 | CTA | 收藏链接，下次直接打开 |",
    "? |\\n| 2 | Screen | Open the tool and paste input |\\n| 3 | Result | Run once and copy output |\\n| 4 | CTA | Bookmark for next time |"],
  ["(kv.topic || '解决方案')", "(kv.topic || 'a solution')"],
  ["' -> 长度 '", "' -> length '"],
  ["' ⚠️ 偏长' : ' ✅ 可接受'", "' ⚠️ long' : ' ✅ OK'"],
  ["|| '本工具'", "|| 'this tool'"],
  ["' 免费吗？\\nA: 免费，无需注册。\\n\\nQ: 会上传我的数据吗？\\nA: 不会，纯前端本地处理。\\n\\nQ: 支持哪些输入格式？\\nA: 支持粘贴文本；复杂格式可先点“填入示例”。\\n\\nQ: 结果不准确怎么办？\\nA: 先检查输入格式，再尝试示例数据对照。'",
    "' free?\\nA: Yes, no signup.\\n\\nQ: Is data uploaded?\\nA: No. Runs locally in your browser.\\n\\nQ: What input formats work?\\nA: Paste plain text; use Load sample for format hints.\\n\\nQ: Wrong output?\\nA: Check input format and compare with the sample.'"],
  ["' | 长度 '", "' | length '"],
  ["'未发现 canonical'", "'No canonical found'"],
  ["'\\n\\n数量: '", "'\\n\\nCount: '"],
  ["' ⚠️ 多个 canonical 可能冲突' : ' ✅'", "' ⚠️ multiple canonicals may conflict' : ' ✅'"],
  ["'(无锚文本)'", "'(no anchor text)'"],
  ["'\\n\\n跳数: '", "'\\n\\nRedirect hops: '"],
  ["'/30 字符'", "'/30 chars'"],
  ["' ⚠️ 超长' : ' ✅'", "' ⚠️ too long' : ' ✅'"],
  ['const re = /(?:TODO|待办|负责|行动项|跟进)[:：]?\\s*(.+)$/gim;', 'const re = /(?:TODO|action item|assigned to|follow-up)[:：]?\\s*(.+)$/gim;'],
  ['const names = Array.from(text.matchAll(/([\\u4e00-\\u9fa5A-Za-z]{2,8})\\s*负责/g)).map((m) => m[1] + \' 负责相关事项\');',
    'const names = Array.from(text.matchAll(/([A-Za-z]{2,20})\\s+owns/gi)).map((m) => m[1] + \' — related action item\');'],
  ["m[1] + ' 负责相关事项'", "m[1] + ' — related action item'"],
  ["'未识别到行动项，可尝试包含“负责”“TODO:”等关键词'", "'No action items found. Try TODO:, assigned to, or action item.'"],
  ["return '目标: '", "return 'Goal: '"],
  ["'\\n\\n1. 明确输入/输出\\n2. 实现核心功能\\n3. 自测示例数据\\n4. 补齐 SEO（title/description/FAQ）\\n5. 部署并加入导航站内链'",
    "'\\n\\n1. Define input/output\\n2. Implement core feature\\n3. Test with sample data\\n4. Add SEO (title/description/FAQ)\\n5. Deploy and link from directory'"],
  ["'（番茄 25 分钟 + 休息 5 分钟）'", "' (Pomodoro 25 min + 5 min break)'"],
  ["return q && a ? '【卡】\\n问: ' + q + '\\n答: ' + a : ''", "return q && a ? 'Card\\nQ: ' + q + '\\nA: ' + a : ''"],
  ["return 'JD 关键词数: '", "return 'JD keywords: '"],
  ["'\\n命中: '", "'\\nMatched: '"],
  ["'\\n命中率(粗): '", "'\\nMatch rate (approx.): '"],
  ["'\\n\\n命中词:\\n'", "'\\n\\nMatched terms:\\n'"],
  ["return 'S（情境）: '", "return 'S (Situation): '"],
  ["'\\nT（任务）: '", "'\\nT (Task): '"],
  ["'\\nA（行动）: '", "'\\nA (Action): '"],
  ["'\\nR（结果）: '", "'\\nR (Result): '"],
  ["(ok ? '通过' : '未通过')", "(ok ? 'pass' : 'fail')"],
  ["' | 格式: ' + (ok ? '18位' : '异常')", "' | format: ' + (ok ? '18-digit' : 'invalid')"],
  ["return '有效邮箱:\\n'", "return 'Valid emails:\\n'"],
  ["'\\n\\n疑似无效:\\n'", "'\\n\\nPossibly invalid:\\n'"],
  ["'(无)'", "'(none)'"],
  ["kv.site + ' 使用 Cookie 改善体验。仅必要 Cookie 默认开启，分析类 Cookie 可拒绝。继续使用即表示你了解本地工具不上传输入数据。'",
    "kv.site + ' uses cookies to improve experience. Essential cookies are on by default; analytics cookies are optional. By continuing you acknowledge this tool does not upload your input.'"],
  ["return 'robots 中 sitemap: '", "return 'Sitemap in robots: '"],
  ["(sitemapInRobots || '未声明')", "(sitemapInRobots || 'not declared')"],
  ["'\\nURL 列表数量: '", "'\\nURL list count: '"],
  ["'\\n建议: sitemap 中的 URL 应都能被 Allow 规则覆盖'", "'\\nTip: URLs in the sitemap should be allowed by robots rules'"],
  ["'| 卖点 ' + (i + 1) + ' | 用户收益 | 证据/场景 |\\n| ' + line + ' | 解决一个明确痛点 | 可在落地页 H2 展示 |",
    "'| Point ' + (i + 1) + ' | User benefit | Proof |\\n| ' + line + ' | Solves a clear pain | Use on landing H2 |"],
  ["return '旧值: '", "return 'Old: '"],
  ["'\\n新值: '", "'\\nNew: '"],
  ["'\\n变化: '", "'\\nChange: '"],
  ["'\\n涨跌幅: '", "'\\nPercent change: '"],
  ["return '基线转化率: '", "return 'Baseline conversion: '"],
  ["'\\n期望提升: '", "'\\nExpected lift: '"],
  ["'\\n每组样本量(粗算): '", "'\\nSample size per group (approx.): '"],
  ["'\\n总样本(两组): '", "'\\nTotal sample (both groups): '"],
  ["return '访问 -> 注册: '", "return 'Visit -> Signup: '"],
  ["'\\n注册 -> 付费: '", "'\\nSignup -> Pay: '"],
  ["'\\n访问 -> 付费: '", "'\\nVisit -> Pay: '"],
  ["return '推荐者: '", "return 'Promoters: '"],
  ["'\\n被动者: '", "'\\nPassives: '"],
  ["'\\n贬损者: '", "'\\nDetractors: '"],
  ["'未统计到状态码'", "'No status codes found'"],
  ["throw new Error('请输入 JSON 数组')", "throw new Error('Enter a JSON array')"],
  ["return '图片总数: '", "return 'Total images: '"],
  ["'\\n缺少 alt: '", "'\\nMissing alt: '"],
  ["'全部图片都有 alt'", "'All images have alt text'"],
  ["'zh-CN'", "'en'"],
  ["(config.keywords || []).join('、')", "(config.keywords || []).join(', ')"]
];

for (const [from, to] of pairs) {
  if (typeof to === 'string') {
    s = s.split(from).join(to);
  } else {
    s = s.replace(from, to);
  }
}

// cookie-banner: always English
s = s.replace(
  /if \(kind === 'cookie-banner'\) \{[\s\S]*?\n  \}/,
  `if (kind === 'cookie-banner') {
    const kv = parseKeyValues(text);
    const site = kv.site || config.name || 'This site';
    return site + ' uses cookies to improve your experience. Essential cookies are enabled by default; analytics cookies are optional. This tool processes input locally and does not upload it.';
  }`
);

fs.writeFileSync(file, s, 'utf8');
console.log('englishize-runtime.js done');
